name: Task Automation
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run at 9 AM UTC every day
    - cron: '0 9 * * *'
  workflow_dispatch:
jobs:
  task-automation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "No requirements.txt found, skipping dependency installation"
        fi
        
    - name: Run automation scripts
      run: |
        python automation/task_manager.py
        python automation/data_processor.py
        
    - name: Update logs
      run: |
        echo "$(date): Task automation completed" >> logs/automation.log
        
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .
        git diff --staged --quiet || git commit -m "Automated task update $(date)"
        git push
