name: Weekly Report Generation

on:
  schedule:
    # Run every Sunday at 6 AM UTC
    - cron: '0 6 * * 0'
  workflow_dispatch:

jobs:
  generate-weekly-report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate weekly report
      run: |
        python automation/report_generator.py --weekly
        
    - name: Process report data
      run: |
        python automation/data_processor.py --report-mode
        
    - name: Update documentation
      run: |
        echo "Weekly report generated on $(date)" >> docs/weekly-reports.md
        
    - name: Archive logs
      run: |
        mkdir -p logs/archives/$(date +%Y)/$(date +%m)
        cp logs/*.log logs/archives/$(date +%Y)/$(date +%m)/ || true
        
    - name: Commit and push changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .
        git diff --staged --quiet || git commit -m "Weekly report generated $(date +%Y-%m-%d)"
        git push
        
    - name: Create weekly summary issue
      uses: actions/github-script@v6
      with:
        script: |
          const title = `Weekly Summary - ${new Date().toISOString().split('T')[0]}`;
          const body = `## Weekly Report Summary\n\nAutomated weekly report has been generated.\n\nCheck the docs/weekly-reports.md file for details.`;
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: title,
            body: body,
            labels: ['automated', 'weekly-report']
          });
